<?php
namespace App\Http\Controllers;
use App\Models\Loan;
use App\Models\Book;
use App\Models\Member;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class LoanController extends Controller {
 public function index(){return response()->json(Loan::with(['book','member'])->latest()->paginate(10));}
 public function mine(Request $r){$member=$r->user()->member;if(!$member)return response()->json(['message'=>'No library membership is linked to this account.'],404);return response()->json($member->loans()->with(['book.category'])->latest()->paginate(10));}
 public function borrowForUser(Request $r){$member=$r->user()->member;if(!$member||$member->status!=='active')return response()->json(['message'=>'An active library membership is required to borrow books.'],422);$d=$r->validate(['book_id'=>'required|exists:books,id','due_date'=>'nullable|date|after_or_equal:today']);$result=DB::transaction(function()use($d,$member){$book=Book::lockForUpdate()->findOrFail($d['book_id']);if($book->available_quantity<1)return ['error'=>response()->json(['message'=>'Book is not available.'],409)];if(Loan::where('book_id',$book->id)->where('member_id',$member->id)->where('status','borrowed')->exists())return ['error'=>response()->json(['message'=>'You already have this book borrowed.'],409)];$loan=Loan::create(['book_id'=>$book->id,'member_id'=>$member->id,'loan_date'=>now()->toDateString(),'due_date'=>$d['due_date']??now()->addDays(14)->toDateString(),'status'=>'borrowed']);$book->decrement('available_quantity');return ['loan'=>$loan->load(['book.category','member'])];});if(isset($result['error']))return $result['error'];return response()->json($result['loan'],201);}
 public function store(Request $r){$d=$r->validate(['book_id'=>'required|exists:books,id','member_id'=>'required|exists:members,id','loan_date'=>'required|date','due_date'=>'required|date|after_or_equal:loan_date']);$result=DB::transaction(function()use($d){$book=Book::lockForUpdate()->findOrFail($d['book_id']);$member=Member::findOrFail($d['member_id']);if($member->status!=='active')return ['error'=>response()->json(['message'=>'Member is inactive.'],422)];if($book->available_quantity<1)return ['error'=>response()->json(['message'=>'Book is not available.'],409)];if(Loan::where('book_id',$book->id)->where('member_id',$member->id)->where('status','borrowed')->exists())return ['error'=>response()->json(['message'=>'Member already has this book borrowed.'],409)];$loan=Loan::create($d+['status'=>'borrowed']);$book->decrement('available_quantity');return ['loan'=>$loan->load(['book','member'])];});if(isset($result['error']))return $result['error'];return response()->json($result['loan'],201);}
 public function show(Loan $loan){return response()->json($loan->load(['book','member']));}
 public function update(Request $r,Loan $loan){if($loan->status==='returned')return response()->json(['message'=>'Returned loans cannot be edited.'],409);$d=$r->validate(['due_date'=>'sometimes|required|date|after_or_equal:'.$loan->loan_date]);$loan->update($d);return response()->json($loan->load(['book','member']));}
 public function destroy(Loan $loan){if($loan->status==='borrowed')return response()->json(['message'=>'Return the book before deleting the loan.'],409);$loan->delete();return response()->json(['message'=>'Loan deleted']);}
 public function returnBook(Loan $loan){if($loan->status==='returned')return response()->json(['message'=>'Book has already been returned.'],409);DB::transaction(function()use($loan){$loan->update(['status'=>'returned','returned_at'=>now()->toDateString()]);Book::whereKey($loan->book_id)->increment('available_quantity');});return response()->json(['message'=>'Book returned successfully','loan'=>$loan->fresh()->load(['book','member'])]);}
}
